### PR TITLE
Allow to pass in inline styles

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Great component! Would love to be able to pass in inline styles though.

**Comment by Fauntleroy** [comment]
signature_thumbs_up

**Comment by KyleAMathews** [comment]
Did you merge the PR?

**Comment by Fauntleroy** [comment]
I didn't! D:

**Comment by Fauntleroy** [comment]
(Sorry about that, very distracted by http://nodeschool.io/oakland/. Check it out sometime!)

**Comment by KyleAMathews** [comment]
No worries! Thanks!

**Pull request merged**
