### PR TITLE
Pass event object to onShow and onHide handlers

### PR DESCRIPTION
**Pull request by allenkim67**
I'd like to pass the event object to the handlers because I want to call stopPropagation because my dropdown is in a component that has its own click handler that I want to avoid triggering.

### CODE REVIEW

**Comment by Fauntleroy** [comment]
Could you achieve the same thing if something like this were possible?

```jsx
<Dropdown>
  <DropdownTrigger
    onClick={ function (event) { event.stopPropagation(); }}>
    Dropdown Trigger
  </DropdownTrigger>
  <DropdownContent>...</DropdownContent>
</Dropdown>
```

**Comment by allenkim67** [comment]
Yes, I think that would work. Thanks for taking a look.

**Comment by Fauntleroy** [comment]
@allenkim67 This should fix your issue: https://github.com/Fauntleroy/react-simple-dropdown/commit/3e355cc8348941730de38792d6c0849c5145accf

**Comment by DoubleYo** [comment]
Hello,

When I use the @Fauntleroy solution's above 
```js
onClick={ function (event) { event.stopPropagation(); }}
```
I got `Cannot read property 'stopPropagation' of undefined`
The event params is actually `undefined` when I log it.

This is related to this PR ?

**Comment by Fauntleroy** [comment]
@DoubleYo which version of `react-simple-dropdown` are you using?

**Comment by DoubleYo** [comment]
I am using the 2.0.0

**Comment by Fauntleroy** [comment]
@DoubleYo Can you create a new issue and provide a larger code example? I'm interested in seeing how you use `Dropdown`, `DropdownTrigger`, and `DropdownContent`.

**Comment by Fauntleroy** [comment]
I'm closing this pull request due to inactivity.

**Pull request closed without merging**
