### PR TITLE
Support for custom activeClassName & tagName

### PR DESCRIPTION
**Pull request by selvagsz**
This PR allows you to specify custom active class name & tag name for the dropdown components. This customization will allow to reuse the components seamlessly with UI frameworks like bootstrap without need of any custom css. Something like

```jsx
<Dropdown component="li" activeClassName="open">
  <DropdownTrigger class="dropdown-toggle">
    {modeFormatted} <span class="caret" />
  </DropdownTrigger>
  <DropdownContent component="ul" class="dropdown-menu">
    <li><a>Test Mode</a></li>
    <li><a>Live Mode</a></li>
  </DropdownContent>
</Dropdown>
```

**Before - Rendered DOM**
```html
<li>
    <div class="dropdown dropdown--active ">
        <a class="dropdown__trigger dropdown-toggle">
            <!-- react-text: 11 -->Test
            <!-- /react-text -->
            <!-- react-text: 12 -->
            <!-- /react-text --><span class="caret"></span></a>
        <div class="dropdown__content dropdown-menu">
            <ul>
                <li><a>Test Mode</a></li>
                <li><a>Live Mode</a></li>
            </ul>
        </div>
    </div>
</li>
```

**After - Rendered DOM**
```html
<li class="dropdown open">
    <a data-toggle="dropdown" class="dropdown__trigger dropdown-toggle">
        <!-- react-text: 11 -->Test
        <!-- /react-text -->
        <!-- react-text: 12 -->
        <!-- /react-text --><span class="caret"></span></a>
    <ul class="dropdown__content dropdown-menu">
        <li><a>Test Mode</a></li>
        <li><a>Live Mode</a></li>
    </ul>
</li>
```

### CODE REVIEW

**Comment by Fauntleroy** [comment]
This seems like a good change, but I want to think more on how to handle customizing class names. Maybe an object like so?

```js
const customClassNames = {
  active: 'drop-active'
};
```

Though I guess the active class is the only one that can't be handled by setting `className` manually on the component....

**Comment by selvagsz** [comment]
@Fauntleroy Sounds like a good idea & one can configure the class globally
```js

import Dropdown from 'react-simple-dropdown'

Dropdown.customClasses = {
  active: 'open'
}
```

**Comment by selvagsz** [comment]
@Fauntleroy Any updates here please ?

**Comment by Fauntleroy** [comment]
@selvagsz I haven't seen any other people request this feature, so until it gets more demand I've decided to pass on it.

**Comment by tonytonyjan** [comment]
I am maintaining a legacy project that has already token `dropdown` and `dropdown--active` class names, making it extremely to integrate with react-simple-dropdown. It would be awesome to have this feature.

**Comment by bologer** [comment]
@Fauntleroy it would be great to override `dropdown` class and all its prefixes to you own. I have a widget, which is shared across multiple websites and sometimes such abstract class can cause style conflicts.

**Pull request closed without merging**
