### PR TITLE
adjusted the onShow & onHide to be fired after active state is applied.

### PR DESCRIPTION
**Pull request by omerman**

### CODE REVIEW

**Comment by Fauntleroy** [comment]
At first glance this looks pretty good, I'll ruminate on it a bit just to be sure there won't be any weird side effects.

If possible, it'd be great to see a test that ensures that this fixes the issue you raised.

**Comment by omerman** [comment]
Added tests. Also, I've made some small(and valuable) modifications to test structure because the `TestApp` was rendered once, and the dropdown components state is not reset each time so if you enter a test that opens/closes the dropdown, it could effect other tests and their results.
So I added the rendering part to be done separately  on each test, I suggest doing so in all of the tests, I will be glad to do it if you'd like( takes 2 minutes :-) ).

**Comment by Fauntleroy** [comment]
Thanks for this, I'll merge it in and make some adjustments after the fact. Expect this to be released in `3.0.0` sometime over the weekend.

**Comment by omerman** [comment]
Great. Thanks!

**Pull request merged**
